### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Teedie** [loganp333/benevolence#1]
Doesn't work, all it says is "[Errno 13] Permission Denied".

**Comment by loganp333** [comment]
Hey! So the issue here is that I accidentally left my catch statements whilst I was debugging this. Otherwise, it grabs tokens perfectly fine. A token can be found in the necessary files without granting admin permissions; however, a lot of the time, the token doesn't spawn up in local storage.

Thank you for letting me know about the catch statements, I am going to make the program seem less conspicuous.

**Comment by Teedie** [comment]
oke thanks :3

**Comment by loganp333** [comment]
Np! :)
